<?php

if (isset($_SESSION['CAMPAIGN_TEMP_PROCESS_ID'])) {
    $CAMPAIGN_TEMP_PROCESS_ID = $_SESSION['CAMPAIGN_TEMP_PROCESS_ID'];
} else {
    $CAMPAIGN_TEMP_PROCESS_ID = DATE("Y-m-d-") . rand(0000, 999999) . "-" . random_bytes(50);
    $_SESSION['CAMPAIGN_TEMP_PROCESS_ID'] = SECURE($CAMPAIGN_TEMP_PROCESS_ID, "e");
}


if (isset($_GET['SELECTED_SENDER_EMAIL_ID'])) {
    $SELECTED_SENDER_EMAIL_ID = $_GET['SELECTED_SENDER_EMAIL_ID'];
    $_SESSION['SELECTED_SENDER_EMAIL_ID'] = $SELECTED_SENDER_EMAIL_ID;
} else {
    if (isset($_SESSION['SELECTED_SENDER_EMAIL_ID'])) {
        $SELECTED_SENDER_EMAIL_ID = $_SESSION['SELECTED_SENDER_EMAIL_ID'];
    } else {
        $SELECTED_SENDER_EMAIL_ID = 0;
    }
}

if (isset($_GET['SELECTED_EMAIL_TEMPLATE_ID'])) {
    $SELECTED_EMAIL_TEMPLATE_ID = $_GET['SELECTED_EMAIL_TEMPLATE_ID'];
    $_SESSION['SELECTED_EMAIL_TEMPLATE_ID'] = $SELECTED_EMAIL_TEMPLATE_ID;
} else {
    if (isset($_SESSION['SELECTED_EMAIL_TEMPLATE_ID'])) {
        $SELECTED_EMAIL_TEMPLATE_ID = $_SESSION['SELECTED_EMAIL_TEMPLATE_ID'];
    } else {
        $SELECTED_EMAIL_TEMPLATE_ID = 0;
    }
}
